language: node_js
node_js:
  - "9"
sudo: true

branches:
  only:
  - master

before_deploy:
  - ./server/run.sh
  - ./client/run.sh

deploy:
  # deploy app as api server
  - provider: heroku
    skip_cleanup: true
    api-key:
      secure: $HEROKU_API_KEY
    app: lms-fiu-fb

after_deploy:
# Procfile is only used for client, delete it to let server run 'npm start'
- rm Procfile